<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cookie_control"
 *
 * Auto generated by Extension Builder 2015-12-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cookie Control',
	'description' => 'Cookie Control ',
	'category' => 'plugin',
	'author' => 'SIJU E RAJU, HOJA.M.A',
	'author_email' => 'siju.er@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);